MyWeb/MyWeb/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasklist.urls')),
]

MyWeb/tasklist/urls.py
from django.urls import path
from . import views

app_name = 'tasklist'

urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('insert/', views.insert, name='insert'),
    path('delete/<int:id>/', views.delete, name='delete'),
    path('update/<int:id>/', views.update, name='update'),
    path('show/', views.show, name='show')
]

MyWeb/tasklist/models.py
from django.db import models

from django.conf import settings

# Create your models here.

class Task(models.Model):
    user =  models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE, null=True)
    course = models.CharField(max_length=100)
    description = models.TextField()
    date = models.DateField()
    time = models.TimeField()
    done = models.BooleanField(default=False)
    class Meta:
        db_table = 'Tasks'

MyWeb/tasklist/views.py
from django.shortcuts import render, redirect
from tasklist.models import Task
from django.contrib.auth.models import User, auth
from django.contrib import messages

# Create your views here.

def home(request):
    return render(request, "home.html")

def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        password1 = request.POST['password1']
        password2 = request.POST['password2']
        if password1 == password2:
            if User.objects.filter(username=username).exists():
                messages.info(request, 'Username Taken')
                return redirect('tasklist:register')
            elif User.objects.filter(email=email).exists():
                messages.info(request, 'Email Taken')
                return redirect('tasklist:register')
            else:
                user = User.objects.create_user(username=username, password=password1, email=email)
                user.save()
                return redirect('tasklist:login')
        else:
            messages.info(request, 'password not matched!')
            return redirect('tasklist:register')
    else:
        return render(request, 'register.html')

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password1']
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            messages.info(request, 'Login Successful')
            return redirect('tasklist:home')
        else:
            messages.info(request, 'Invalid Credentials')
            return redirect('tasklist:login')
    else:
        return render(request, "login.html")

def logout(request):
    auth.logout(request)
    return redirect('tasklist:home')

def insert(request):
    if request.method == 'POST':
        course = request.POST['course']
        description = request.POST['description']
        datetime = request.POST['date'].split('T')
        date = datetime[0]
        time = datetime[1]
        done = False
        task = Task(course=course, description=description, date=date, time=time, done=done, user=request.user)
        task.save()
        return redirect('tasklist:show')
    else:
        return render(request, 'insert.html')

def delete(request, id):
    task = Task.objects.get(id=id)
    task.delete()
    return redirect('tasklist:show')



def update(request, id):
    print(request)
    if request.method == 'POST':
        print(request)
        task = Task.objects.get(id=id)
        task.description = request.POST['description']
        datetime = request.POST['date'].split('T')
        task.date = datetime[0]
        task.time = datetime[1]
        status = request.POST['status']
        if status == 'Done':
            task.done = True
        task.save()

    return redirect('tasklist:show')

def show(request):
    if request.user.is_authenticated:
        tasks = Task.objects.filter(user=request.user).order_by('id')
        return render(request, 'show.html', {'tasks': tasks})
    else:
        return redirect('tasklist:login')

MyWeb/templates/base.html
{% load static %}

<!-- templates/base.html-->
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>
      {% block title %} MyWeb {% endblock %}
    </title>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="author" content="MyWeb"/>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- Bootstrap icons -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css" rel="stylesheet">

    <!-- BigTeta CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
    integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    
    <!-- jquery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  </head>
  <body>
    {% include 'navbar.html' %}
    <main>
      {% block content %}
      {% endblock %}
    </main>

    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- SB Forms JS -->

    <!-- Vendors -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sticky-js/1.3.0/sticky.min.js"
      integrity="sha512-3z3zGiu0PabNyuTAAfznBJFpOg4owG9oQQasE5BwiiH5BBwrAjbfgIe0RCdtHJ0BQV1YF2Shgokbz2NziLnkuQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/plyr/3.7.2/plyr.js"
      integrity="sha512-OlPa3CLz34wRV8+Aq+Zn39Nc5FNHJPPYLeh/ZXjapjWIQl21a4f6gDM6futqnCIF0IQHEQUf3JJkDdLw+mxglA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    {% block scripts %}

    {% endblock scripts %}
    </body>
</html>

MyWeb/templates/home.html
{% extends 'base.html' %}

MyWeb/templates/insert.html
{% extends 'base.html' %}

{% block content %}



{% endblock %}

MyWeb/templates/login.html
{% extends 'base.html' %}

{% block content %}
<div style="background-color: #eee;">
    <div class="row align-items-center vh-100">
        <div class="col-4 mx-auto">
            <div class="card shadow border">
				<div class="card text-black text-center">
                	<div class="card-body d-flex flex-column align-items-center">
						<p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Login</p>
							<form method="POST" action="{% url 'tasklist:login' %}">
								{% csrf_token %}
								<div class="d-flex flex-row align-items-center mb-4">
									<i class="fas fa-user fa-lg me-3 fa-fw"></i>
									<div class="form-outline flex-fill mb-0">
										<input type="text" id="username" name="username" placeholder="Username" class="form-control"><br>
									</div>
								</div>
								<div class="d-flex flex-row align-items-center mb-4">
									<i class="fas fa-lock fa-lg me-3 fa-fw"></i>
									<div class="form-outline flex-fill mb-0">
										<input type="password" id="password1" name="password1" placeholder="Password" class="form-control"><br>
									</div>
								</div>
								<div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
									<button type="submit" class="btn btn-primary btn-lg">Login</button>
								</div>
							</form>    
					</div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

MyWeb/templates/navbar.html
<html lang="en">

<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  	<div class="container-fluid">
		<button
			class="navbar-toggler"
			type="button"
			data-bs-toggle="collapse"
			data-bs-target="#navbarSupportedContent"
			aria-controls="navbarSupportedContent"
			aria-expanded="false"
			aria-label="Toggle navigation"
		>
      	<span class="navbar-toggler-icon"></span>
    	</button>

    	<div class="collapse navbar-collapse" id="navbarSupportedContent">
      		<a class="navbar-brand" href="/">MyWeb</a>
      		<ul class="navbar-nav me-auto mb-2 mb-lg-0 text-uppercase">
				{% if user.is_authenticated %}
					<li class="nav-item">
						<a class="nav-link" href="{% url 'tasklist:show' %}">Task List</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'tasklist:logout' %}">Logout</a>
					</li>
				{% else %}
					<li class="nav-item">
						<a class="nav-link" href="{% url 'tasklist:login' %}">Login</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'tasklist:register' %}">Register</a>
					</li>
				{% endif%}
      		</ul>
    	</div>
  	</div>
</nav>

MyWeb/templates/register.html
{% extends 'base.html' %}
{% block content %}

<div style="background-color: #eee;">
    <div class="row align-items-center vh-100">
        <div class="col-4 mx-auto">
            <div class="card shadow border">
				<div class="card text-black text-center">
                	<div class="card-body d-flex flex-column align-items-center">
						<p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Register</p>
							<form method="POST" action="{% url 'tasklist:register' %}">
								{% csrf_token %}
								<div class="d-flex flex-row align-items-center mb-4">
									<i class="fas fa-user fa-lg me-3 fa-fw"></i>
									<div class="form-outline flex-fill mb-0">
										<input type="text" id="username" name="username" placeholder="Username" class="form-control"><br>
									</div>
								</div>
								<div class="d-flex flex-row align-items-center mb-4">
									<i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
									<div class="form-outline flex-fill mb-0">
										<input type="email" id="email" name="email" placeholder="Email" class="form-control"><br>
									</div>
								</div>
								<div class="d-flex flex-row align-items-center mb-4">
									<i class="fas fa-lock fa-lg me-3 fa-fw"></i>
									<div class="form-outline flex-fill mb-0">
										<input type="password" id="password1" name="password1" placeholder="Password" class="form-control"><br>
									</div>
								</div>
								<div class="d-flex flex-row align-items-center mb-4">
									<i class="fas fa-key fa-lg me-3 fa-fw"></i>
									<div class="form-outline flex-fill mb-0">
										<input type="password" id="password2" name="password2" placeholder="Confirm Password" class="form-control"><br>
									</div>
								</div>
								<div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
									<button type="submit" class="btn btn-primary btn-lg">Register</button>
								</div>
							</form>    
					</div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

MyWeb/templates/show.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-4 shadow-lg p-3 mb-5 bg-body rounded">
    <!-- boton para agregar tarea -->
    <button class="btn btn-primary" 
        data-bs-toggle="modal" 
        data-bs-target="#modalInsertTask"
        v-on:click="resetForm"
        @click="insertTask()">
        Add Task
    </button>
    <table id="table" class="table mt-2 table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th>Course</th>
                <th>Description</th>
                <th>Date</th>
                <th>Time</th>
                <th>Status</th>
                <th>Options</th>
            </tr>
        </thead>
        <tbody>
            {% for task in tasks %}
            <tr>
                <td>{{ task.course }}</td>
                <td>{{ task.description }}</td>
                <td>{{ task.date }}</td>
                <td>{{ task.time }}</td>
                {% if task.done == True %}
                    <td>Done</td>
                {%else %}
                    <td>Pending</td>
                {%endif %}
                <td>
                    <a href="{% url 'tasklist:delete' task.id %}" class="btn btn-danger">Delete</a>
                    <a href="#modalUpdateTask-{{forloop.counter}}" class="btn btn-warning" data-bs-toggle="modal">Update</a>
                </td>
            </tr>
            {% endfor %}
            
        </tbody>
    
    </table>
    
</div>

<!-- Modal Insert -->

<div class="modal fade" id="modalInsertTask" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Add Task</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form action="{% url 'tasklist:insert' %}" method="POST">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="course" class="form-label">Course</label>
                        <select class="form-select" aria-label="Default select example" name="course" v-model="course">
                            <option selected>Compiladores</option>
                            <option value="Análisis y Diseño de Algoritmos">Análisis y Diseño de Algoritmos</option>
                            <option value="Ingeniería de Software">Ingeniería de Software</option>
                            <option value="Base de datos II">Base de datos II</option>
                            <option value="Perú: Temas de la Sociedad Contemporánea">Perú: Temas de la Sociedad Contemporánea</option>
                            <option value="Proyecto Interdisciplinario III">Proyecto Interdisciplinario III</option>
                        </select>
                    </div>
                    <div>
                        <label for="description" class="form-label">Description</label>
                        <textarea class="form-control" id="description" rows="3" name="description" v-model="description"></textarea>
                    </div>
                    <div class="mb-3">
                        <label for="date" class="form-label">Date</label>
                        <input type="datetime-local" class="form-control" id="date" name="date" v-model="date">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Insert</button>
                    </div> 
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Modal Update -->

{% for task in tasks %}
    <div class="modal fade" id="modalUpdateTask-{{forloop.counter}}" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Update Task</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form action="{% url 'tasklist:update' task.id %}" method="POST">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="course" class="form-label">Course</label>
                            <input class="form-control" id ="course" name='course' size=32 value = "{{task.course}}" disabled></input>
                        </div>
                        <div>
                            <label for="description" class="form-label">Description</label>
                            <textarea class="form-control" id="description" rows="3" name='description'>{{task.description}}</textarea>
                        </div>
                        <div class="mb-3">
                            <label for="date" class="form-label">Date</label>
                            <input type="datetime-local" class="form-control" id="date" name="date"></input>
                        </div>
                        <div class="mb-3">
                            <label for="time" class="form-label">Time</label>
                            <select class="form-select" aria-label="Default select example" name="status" v-model="status">
                                <option selected>Pending</option>
                                <option value="Done">Done</option>
                            </select>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">Update</button>
                        </div> 
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endfor %}

{% endblock %}

{% block scripts %}


{% endblock scripts %}